### PR TITLE
add missing properties

### PR DESCRIPTION
**Pull request by Mouvedia**
ref:
- https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html
- https://stackoverflow.com/a/11759353/248058

see also stylelint/stylelint#7764

### CODE REVIEW

**Comment by vio** [comment]
Thank you for the PR @Mouvedia!

`all.json` is generated from the existing json files. We commit it to easily see what changed compared the existing props. If you get the chance, can you please:

1. rebase to get the latest master changes - includes chrome 126 properties https://github.com/known-css/known-css-properties/pull/175/commits/ef32ddbb5679f00c2fa1b066c016a144cdd9d48c
2. run `npm run generate` to build the latest `all.json`
3. update README.md with the safari versions - it would have been great to have all the properties, but this is quite challenging for old versions

**Comment by Mouvedia** [comment]
> `all.json` is generated from the existing json files
> […]
> run `npm run generate` to build the latest `all.json`

I need to create a new file for the properties not present in neither `safari-2.0.json` nor `safari-1.1.json`.
What would you like it to be named?
`misc.json`? `uncategorised.json`? `rest.json`?

**Comment by vio** [comment]
@Mouvedia what is the source of this properties?

we are currently merging properties extracted automatically from browsers and w3c

**Comment by Mouvedia** [comment]
I have put the references in [OP](https://github.com/known-css/known-css-properties/pull/174#issue-2356864103).
We have already fixed it on our side but I took the time to add it here thinking it would be better for the community.
I didn't add a descriptor though, because it's not technically a property per se.

Ill add the missing file; gimme a moment.

**Comment by Mouvedia** [comment]
> update README.md with the safari versions - it would have been great to have all the properties, but this is quite challenging for old versions

WIP

**Comment by Mouvedia** [comment]
1. [x] rebase
2. [x] `npm run generate`
3. [x] update README.md

**Review by vio — APPROVED** [review]
👍

**Pull request merged**
