### PR TITLE
update W3C data

### PR DESCRIPTION
**Pull request by konojunya**
update W3C data!

### CODE REVIEW

**Comment by konojunya** [comment]
so, sorry.
It supports up to Chrome 81. I have to pull up to the current latest version of Chrome 85 and put an appropriate one in the source.

**Comment by vio** [comment]
Thank you @konojunya! I'm preparing a new release with the latest data, but can you please remove the .gitignore or push it as a different commit?

**Comment by konojunya** [comment]
ok :)

**Comment by vio** [comment]
@konojunya I released [`0.20.0`](https://www.npmjs.com/package/known-css-properties), thanks again!

**Pull request merged**
